/*
 */
package vista;

import static extras.Colores_Dimensiones.AZUL;
import extras.ModeloAlquiler;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Alquiler;

/**
 *
 * @author Escoz
 */
public class DialogoAlquiler extends javax.swing.JDialog {
    
    private VistaPrincipal padre;
    private ModeloAlquiler modelo_tabla;

    /**
     * Creates new form DialogoAlquiler
     */
    public DialogoAlquiler(VistaPrincipal padre, boolean modal) {
        super(padre, modal);
        
        this.padre = padre;
        this.modelo_tabla = new ModeloAlquiler();
        
        initComponents();
    }
    
    public void muestraAlquileres(ArrayList<Alquiler> alquileres) {
        
        ModeloAlquiler modelo = (ModeloAlquiler) tabla_alquileres.getModel();
        modelo.addAlquileres(alquileres);
        
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_alquileres = new javax.swing.JPopupMenu();
        popMenu_verLibro = new javax.swing.JMenuItem();
        popMenu_verUsuario = new javax.swing.JMenuItem();
        panel_busqueda = new javax.swing.JPanel();
        campo_busqueda = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        boton_busqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alquileres = new javax.swing.JTable();

        popMenu_verLibro.setText("Datos del libro");
        pop_alquileres.add(popMenu_verLibro);

        popMenu_verUsuario.setText("Datos del usuario");
        pop_alquileres.add(popMenu_verUsuario);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de alquileres");
        setPreferredSize(new java.awt.Dimension(800, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panel_busqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 0, 10));
        panel_busqueda.setLayout(new javax.swing.BoxLayout(panel_busqueda, javax.swing.BoxLayout.LINE_AXIS));

        campo_busqueda.setText("Introduce tu busqueda...");
        panel_busqueda.add(campo_busqueda);
        panel_busqueda.add(filler1);

        boton_busqueda.setBackground(AZUL);
        boton_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        boton_busqueda.setText("Buscar");
        boton_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busquedaActionPerformed(evt);
            }
        });
        panel_busqueda.add(boton_busqueda);

        getContentPane().add(panel_busqueda);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createTitledBorder("")));

        tabla_alquileres.setAutoCreateRowSorter(true);
        tabla_alquileres.setModel(modelo_tabla);
        tabla_alquileres.setComponentPopupMenu(pop_alquileres);
        tabla_alquileres.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_alquileres);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setLocationRelativeTo(padre);
    }//GEN-LAST:event_formComponentShown

    private void boton_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busquedaActionPerformed
        JOptionPane.showMessageDialog(this, "En construcción...",
                "", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_boton_busquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_busqueda;
    private javax.swing.JTextField campo_busqueda;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_busqueda;
    private javax.swing.JMenuItem popMenu_verLibro;
    private javax.swing.JMenuItem popMenu_verUsuario;
    private javax.swing.JPopupMenu pop_alquileres;
    private javax.swing.JTable tabla_alquileres;
    // End of variables declaration//GEN-END:variables
}
