/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import controlador.Controlador;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.Libro;
import modelo.Persona;

/**
 *
 * @author Escoz
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private Controlador controlador;
    private DefaultListModel modelo_lista;

    private Persona persona_alquilada;

    private DialogoPersona dialogoPersona;

    /**
     * Creates new form Vista
     */
    public VistaPrincipal(Controlador controlador) {
        this.controlador = controlador;
        this.modelo_lista = new DefaultListModel();
        this.dialogoPersona = new DialogoPersona(this, true);

        //setLookAndFeel();
        initComponents();
        setModeloListaLibros();

    }

    private void setModeloListaLibros() {
        modelo_lista.clear();
        ArrayList<Libro> libros = controlador.getLibros();

        for (Libro libro : libros) {

            String titulo = (String) libro.getDetalles_libro().get("titulo");
            modelo_lista.addElement(titulo);
        }

        lista_libros.setModel(modelo_lista);
    }

    private void setModeloListaLibros(ArrayList<Libro> libros_encontrados) {
        modelo_lista.clear();

        if (!libros_encontrados.isEmpty()) {
            for (Libro libro : libros_encontrados) {

                String titulo = (String) libro.getDetalles_libro().get("titulo");
                modelo_lista.addElement(titulo);
            }
        } else {
            modelo_lista.addElement("- Sin resultados -");
        }
        lista_libros.setModel(modelo_lista);
    }

    private void gestionaPersonaAlquiler() {
        if (persona_alquilada != null) {
            boton_detallesUsuario.setEnabled(true);
            label_usuarioAlquiler.setText(persona_alquilada.getNombreCompleto());
        } else {
            boton_detallesUsuario.setEnabled(false);
            label_usuarioAlquiler.setText("- Sin Datos -");
        }
    }

    @Deprecated
    private void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }

    private void rellenaCamposLibro(Libro libro) {
        Map detalles_libro = libro.getDetalles_libro();
        String isbn = (String) detalles_libro.get("isbn");
        String titulo = (String) detalles_libro.get("titulo");
        String autor = (String) detalles_libro.get("autor");
        String fecha = (String) detalles_libro.get("fecha_publicacion");

        campo_isbn.setText(isbn);
        campo_titulo.setText(titulo);
        campo_fecha.setText(autor);
        campo_autor.setText(fecha);
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_buscador = new javax.swing.JPanel();
        campo_busquedaLibro = new javax.swing.JTextField();
        boton_buscarLibro = new javax.swing.JButton();
        boton_limpiarBusqueda = new javax.swing.JButton();
        panel_datos = new javax.swing.JPanel();
        panel_listadoLibros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_libros = new javax.swing.JList<>();
        panel_detallesLibro = new javax.swing.JPanel();
        label_isbn = new javax.swing.JLabel();
        campo_isbn = new javax.swing.JTextField();
        label_titulo = new javax.swing.JLabel();
        campo_titulo = new javax.swing.JTextField();
        label_autor = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        campo_autor = new javax.swing.JTextField();
        campo_fecha = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panel_datosUsuario = new javax.swing.JPanel();
        boton_detallesUsuario = new javax.swing.JButton();
        label_usuarioAlquiler = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca App");
        setMinimumSize(new java.awt.Dimension(700, 425));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panel_buscador.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        panel_buscador.setPreferredSize(new java.awt.Dimension(600, 40));
        panel_buscador.setLayout(new java.awt.GridBagLayout());

        campo_busquedaLibro.setText("Introduce un titulo...");
        campo_busquedaLibro.setToolTipText("Busca un libro por titulo");
        campo_busquedaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_busquedaLibroMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panel_buscador.add(campo_busquedaLibro, gridBagConstraints);

        boton_buscarLibro.setBackground(new java.awt.Color(102, 204, 255));
        boton_buscarLibro.setText("Buscar");
        boton_buscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panel_buscador.add(boton_buscarLibro, gridBagConstraints);

        boton_limpiarBusqueda.setText("Limpiar");
        boton_limpiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarBusquedaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_buscador.add(boton_limpiarBusqueda, gridBagConstraints);

        getContentPane().add(panel_buscador);

        panel_datos.setLayout(new java.awt.GridBagLayout());

        panel_listadoLibros.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 1), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Libros"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5))));
        panel_listadoLibros.setPreferredSize(new java.awt.Dimension(300, 360));
        panel_listadoLibros.setLayout(new java.awt.GridLayout(1, 0));

        lista_libros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista_libros.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                libroSeleccionado(evt);
            }
        });
        jScrollPane1.setViewportView(lista_libros);

        panel_listadoLibros.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panel_datos.add(panel_listadoLibros, gridBagConstraints);

        panel_detallesLibro.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Detalles del Libro")));
        panel_detallesLibro.setPreferredSize(new java.awt.Dimension(300, 300));
        panel_detallesLibro.setLayout(new java.awt.GridBagLayout());

        label_isbn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_isbn.setText("ISBN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panel_detallesLibro.add(label_isbn, gridBagConstraints);

        campo_isbn.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_detallesLibro.add(campo_isbn, gridBagConstraints);

        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_titulo.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panel_detallesLibro.add(label_titulo, gridBagConstraints);

        campo_titulo.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_detallesLibro.add(campo_titulo, gridBagConstraints);

        label_autor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_autor.setText("Autor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panel_detallesLibro.add(label_autor, gridBagConstraints);

        label_fecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_fecha.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panel_detallesLibro.add(label_fecha, gridBagConstraints);

        campo_autor.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_detallesLibro.add(campo_autor, gridBagConstraints);

        campo_fecha.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_detallesLibro.add(campo_fecha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        panel_detallesLibro.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.4;
        panel_datos.add(panel_detallesLibro, gridBagConstraints);

        panel_datosUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Datos del Alquiler")));
        panel_datosUsuario.setName(""); // NOI18N
        panel_datosUsuario.setPreferredSize(new java.awt.Dimension(300, 100));
        panel_datosUsuario.setLayout(new java.awt.BorderLayout());

        boton_detallesUsuario.setBackground(new java.awt.Color(102, 204, 255));
        boton_detallesUsuario.setText("Ver detalles...");
        boton_detallesUsuario.setEnabled(false);
        boton_detallesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_detallesUsuarioActionPerformed(evt);
            }
        });
        panel_datosUsuario.add(boton_detallesUsuario, java.awt.BorderLayout.PAGE_END);

        label_usuarioAlquiler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuarioAlquiler.setText("- Sin Datos -");
        panel_datosUsuario.add(label_usuarioAlquiler, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panel_datos.add(panel_datosUsuario, gridBagConstraints);

        getContentPane().add(panel_datos);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void libroSeleccionado(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_libroSeleccionado
        JList lista = (JList) evt.getSource();

        if (lista.hasFocus()) {
            if (!lista.getValueIsAdjusting()) {
                String titulo_libro = (String) lista.getSelectedValue();

                if (!titulo_libro.equals("- Sin resultados -")) {
                    Libro libro_seleccionado = controlador.getInfoLibro(titulo_libro);
                    String isbn_libro = (String) libro_seleccionado.getDetalles_libro().get("isbn");
                    persona_alquilada = controlador.getInfoAlquileres(isbn_libro);

                    rellenaCamposLibro(libro_seleccionado);
                    gestionaPersonaAlquiler();
                }
            }
        }
    }//GEN-LAST:event_libroSeleccionado

    private void campo_busquedaLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_busquedaLibroMouseClicked
        JTextField campo = (JTextField) evt.getSource();
        campo.setText("");
    }//GEN-LAST:event_campo_busquedaLibroMouseClicked

    private void boton_buscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarLibroActionPerformed
        String busqueda = campo_busquedaLibro.getText();

        ArrayList<Libro> libros_encontrados = controlador.buscaLibroTitulo(busqueda);
        setModeloListaLibros(libros_encontrados);

    }//GEN-LAST:event_boton_buscarLibroActionPerformed

    private void boton_limpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarBusquedaActionPerformed
        setModeloListaLibros();
        campo_busquedaLibro.setText("Introduce un titulo...");
        label_usuarioAlquiler.setText("- Sin Datos -");
        boton_detallesUsuario.setEnabled(false);
        persona_alquilada = null;

        rellenaCamposLibro(new Libro());
    }//GEN-LAST:event_boton_limpiarBusquedaActionPerformed

    private void boton_detallesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_detallesUsuarioActionPerformed
        dialogoPersona.rellenaDatosPersona(persona_alquilada);
        dialogoPersona.setVisible(true);
    }//GEN-LAST:event_boton_detallesUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscarLibro;
    private javax.swing.JButton boton_detallesUsuario;
    private javax.swing.JButton boton_limpiarBusqueda;
    private javax.swing.JTextField campo_autor;
    private javax.swing.JTextField campo_busquedaLibro;
    private javax.swing.JTextField campo_fecha;
    private javax.swing.JTextField campo_isbn;
    private javax.swing.JTextField campo_titulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_autor;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_isbn;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_usuarioAlquiler;
    private javax.swing.JList<String> lista_libros;
    private javax.swing.JPanel panel_buscador;
    private javax.swing.JPanel panel_datos;
    private javax.swing.JPanel panel_datosUsuario;
    private javax.swing.JPanel panel_detallesLibro;
    private javax.swing.JPanel panel_listadoLibros;
    // End of variables declaration//GEN-END:variables
}
